name: Latest Release Monitor
on:
  schedule:
    - cron: 0/5 * * * *
  repository_dispatch:
    types: [trigger-latest-release-monitor]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: stable
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Install Storage Module
        run: npm install @azure/storage-blob@12.1.1
      - name: Run Latest Release Monitor
        uses: ./actions/latest-release-monitor
        with:
          storageKey: ${{secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING}}
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
Warning: Unexpected input(s) 'appInsightsKey', valid inputs are ['token', 'storageKey']
##[debug]Loading env
run-name: Run ./actions/latest-release-monitor
with:
/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: token
    at Object.getInput (/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118:15)
    at getRequiredInput (/home/runner/work/vscode/vscode/actions/common/utils.js:15:41)
    at Object.<anonymous> (/home/runner/work/vscode/vscode/actions/latest-release-monitor/index.js:12:44)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
    Warning: Unexpected input(s) 'appInsightsKey', valid inputs are ['token', 'storageKey']
Run ./actions/latest-release-monitor
  with:
/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: token
    at Object.getInput (/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118:15)
    at getRequiredInput (/home/runner/work/vscode/vscode/actions/common/utils.js:15:41)
    at Object.<anonymous> (/home/runner/work/vscode/vscode/actions/latest-release-monitor/index.js:12:44)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
    
