Warning: Unexpected input(s) 'appInsightsKey', valid inputs are ['token', 'storageKey']
Run ./actions/latest-release-monitor
  with:
/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: token
    at Object.getInput (/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118:15)
    at getRequiredInput (/home/runner/work/vscode/vscode/actions/common/utils.js:15:41)
    at Object.<anonymous> (/home/runner/work/vscode/vscode/actions/latest-release-monitor/index.js:12:44)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
    Warning: Unexpected input(s) 'appInsightsKey', valid inputs are ['token', 'storageKey']
Run ./actions/latest-release-monitor
  with:
/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: token
    at Object.getInput (/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118:15)
    at getRequiredInput (/home/runner/work/vscode/vscode/actions/common/utils.js:15:41)
    at Object.<anonymous> (/home/runner/work/vscode/vscode/actions/latest-release-monitor/index.js:12:44)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
    
